#!/bin/bash
compile_command=
res=$(echo $GEDIT_CURRENT_DOCUMENT_NAME | grep --ignore-case --count ".cpp"$)

if [ "$res" = "1" ]
then
	compile_command="g++ -W -Wall -Wextra -O2"
else
	compile_command="gcc -lm -W -Wall -Wextra -O2"
fi
	

if $compile_command $GEDIT_CURRENT_DOCUMENT_NAME
then
	printf "Success"
fi

exit 0

