#!/bin/sh

set -e

SCRIPT_DIR="$( cd -P "$( dirname "$0" )" && pwd )"

echo "Copying files to home"
for i in $(ls -A $SCRIPT_DIR/home); do
    cp -R $SCRIPT_DIR/home/$i $HOME
done

echo "Installing VIM Plugins"
#Open Vim, run BundleInstall! (new plugin/update plugin), 
#run BundleClean (remove deleted plugin), then quit (via q).
vim +BundleInstall! +BundleClean +q /dev/zero
