export EDITOR=vim
# emacs editing mode
bindkey -e 

######################################## misc options {{{

# type '<dir>' instead of 'cd <dir>'
setopt autocd

# http://zsh.sourceforge.net/Intro/intro_2.html#SEC2
setopt extendedglob 

setopt nobeep
########################################}}}

##### history {{{

# Name of the file in which history is stored
HISTFILE=~/.zsh_histfile
HISTSIZE=100000
SAVEHIST=100000

# prevent history from recording duplicated entries
setopt hist_ignore_all_dups 

# Prevent entries from being recorded into a history by preceding them with at least one space. 
setopt hist_ignore_space 

setopt appendhistory
#####}}}

# Directory history. http://zsh.sourceforge.net/Intro/intro_6.html
# cd -3
# cd =3/fun
# dirs -v
DIRSTACKSIZE=8 # keeps the directory stack from getting too large
setopt autopushd # made cd act like pushd
setopt pushdminus # swapped the meaning of cd +1 and cd -1
setopt pushdsilent # keeps the shell from printing the directory stack each time we do a cd
setopt pushdtohome


zstyle :compinstall filename '/home/prakash/.zshrc'

# enable the famous zsh tab-completion system
autoload -Uz compinit
compinit

#zstyle ':completion:*:descriptions' format '%U%B%d%b%u'
#zstyle ':completion:*:warnings' format '%BSorry, no matches for: %d%b'

export PS1="[%B%* %n@%M %d%b]%(?.. (%?%))
$"

#command aliases {{{
alias ls='ls --classify --color=auto'
alias ll='ls -l'
alias cp='cp -i'
alias mv='mv -i'
alias grep='grep --color=auto'

alias gcc='gcc -lm -W -Wall -Wextra -O2'
alias g++='g++ -W -Wall -Wextra -O2'
#}}}
